In [1]:
import torchaudio
from speechbrain.pretrained import EncoderClassifier

In [2]:
province_code = EncoderClassifier.from_hparams(
    source="pretrained-model-src", 
    savedir="pretrained-model-save"
)

{'starting_index': 0}


In [3]:
signal = province_code.load_audio("/data/MTDATA/fn-2-018/root/person/st/gw/collectorgw88/st_set1_collectorgw88_speakergw407_8_11.wav")
prediction =  province_code.classify_batch(signal)
print(prediction)

(tensor([[-1.1454, -3.3068, -1.4048, -3.6288, -0.9854]]), tensor([-0.9854]), tensor([4]), ['cc: 충청'])


In [6]:
signal = province_code.load_audio("/data/MTDATA/fn-2-018/root/person/st/gs/collectorgs31/st_set2_collectorgs31_speakergs98_68_6.wav")
prediction =  province_code.classify_batch(signal)
print(prediction)

(tensor([[-7.5612, -0.3471, -1.3751, -8.1841, -3.2270]]), tensor([-0.3471]), tensor([1]), ['gs: 경상'])


In [7]:
signal = province_code.load_audio("/data/MTDATA/fn-2-018/root/person/st/jl/collectorjl20/st_set3_collectorjl20_speakerjl218_31_12.wav")
prediction =  province_code.classify_batch(signal)
print(prediction)

(tensor([[-1.7571, -3.0018, -1.1641, -2.0058, -1.1056]]), tensor([-1.1056]), tensor([4]), ['cc: 충청'])


In [8]:
signal = province_code.load_audio('/data/MTDATA/fn-2-018/root/person/st/jj/collectorjj10/st_set1_collectorjj10_speakerjj13_81_10.wav')
prediction =  province_code.classify_batch(signal)
print(prediction)

(tensor([[-9.4178e+00, -1.1504e+01, -8.5810e+00, -5.9206e-04, -8.0697e+00]]), tensor([-0.0006]), tensor([3]), ['jj: 제주'])


In [9]:
signal = province_code.load_audio('/data/MTDATA/fn-2-018/root/person/st/cc/collectorcc46/st_set1_collectorcc46_speakercc308_46_7.wav')
prediction =  province_code.classify_batch(signal)
print(prediction)

(tensor([[-5.4047, -5.3909, -5.1641, -4.6967, -0.0242]]), tensor([-0.0242]), tensor([4]), ['cc: 충청'])


In [14]:
print(prediction[1].exp())

tensor([0.2031])


In [19]:
print(prediction[3])

['jl: 전라']


In [20]:
emb =  province_code.encode_batch(signal)

In [21]:
print(emb.shape)

torch.Size([1, 1, 256])
